[package]
name = "steam_server_disable"
version = "0.1.0"
authors = ["ishbosamiya <ishbosamiya@gmail.com>"]
edition = "2018"

[[bin]]
name = "steam_server_disable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
curl = "0.4.36"
egui_glfw = { git = "https://github.com/ishbosamiya/egui_glfw.git", tag = "v0.2.0" }
glfw = "0.41"
gl = "0.14"
nalgebra-glm = "0.13"
icmp-socket = "0.1"
log = "0.4"
lazy_static = "1.4"

[target.'cfg(unix)'.dependencies]
iptables = "0.4.3"
sudo = "0.6"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1"

[patch.crates-io]
# current crates io version does not support timeout correctly
icmp-socket = { git = "https://github.com/zaphar/icmp-socket.git", branch = "master" }

[profile.release]
debug = 1