[package]
name = "steam_server_disable"
version = "0.1.0"
authors = ["ishbosamiya <ishbosamiya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
curl = "0.4.36"
iptables = "0.4.3"
iced = { version = "0.3.0", features = ["async-std", "glow"] }
fastping-rs = "0.2.2"
crossbeam-channel = "0.5.1"